app = "pocketrisu"
primary_region = "nrt"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 6001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "pocketrisu_save"
  destination = "/app/save"
